<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "./code/model_pair_distance.py", line 53, in <module>
    model1 = load_checkpoint(args, file_name1)
  File "/home/bhawks/loss_landscape/loss_landscape_taxonomy/workspace/src_jet/code/model.py", line 47, in load_checkpoint
    model.load_state_dict(checkpoint["state_dict"])
UnboundLocalError: local variable 'model' referenced before assignment
